spring:
  profiles:
    active: dev

logging:
  level:
    root: INFO
    ### 패키지만 DEBUG 처리
    spring.boot.log4j2.demo: DEBUG
---
spring:
  profiles: dev
logging:
  config: classpath:log4j2-dev.xml

---
spring:
  profiles: prod
logging:
  config: classpath:log4j2-prod.xml
